Feature/powerups
DanielNijkamp/FlippinWorlds pull request #15
Opened 2024-03-08 14:12 UTC by RossTubes

Worked on all the powerups they should work properly in the scene now. Double Bounce/Points and an extra ball powerups are all added to the scene and tested.

2024-03-09 16:38 UTC, DanielNijkamp requested changes
Slordig werk, kijk goed naar code conventie. voor het mergen haal alle comments weg, kijk goed naar benamingen

2024-03-09 16:38 UTC, DanielNijkamp commented on Assets/Prefabs/bally.prefab
Geef dit een beter naam zoals Ball.prefab ipv bally

2024-03-09 16:38 UTC, DanielNijkamp commented on Assets/Scripts/PowerUps/PowerUp.cs
> +//ienumerator duration add
```suggestion
```
Haal alle comments uit deze class.

2024-03-09 16:38 UTC, DanielNijkamp commented on Assets/Scripts/PowerUps/PowerUp.cs
> +    public float respawnTime = 10f; // Adjust the respawn time in the Unity Inspector
```suggestion
   [SerializeField] protected float _respawnTime; 
```
private of protected met underscore + camelCase

Dit moet protected zijn als dit in derived classes word gebruikt. anders moet het private zijn

Maak het serializable zodat het in de inspector aangepast kan worden en geen hard-coded values zoals die value assignment op het einde. alles via de inspector

2024-03-09 16:38 UTC, DanielNijkamp commented on Assets/Scripts/PowerUps/PowerUp.cs
> +    public GameObject model;
```suggestion
    [SerializeField] protected GameObject _model;
```
Zelfde hier

2024-03-09 16:38 UTC, DanielNijkamp commented on Assets/Scripts/PowerUps/PowerUp.cs
> +    }
```suggestion
```
Geen classes binnen classes dit is slecht

2024-03-09 16:38 UTC, DanielNijkamp commented on Assets/Scripts/PowerUps/PowerUp.cs
> +}
```suggestion
```
Zelfde advies hier

2024-03-09 16:38 UTC, DanielNijkamp commented on Assets/Scripts/PowerUps/PowerUp.cs
> +    }
```suggestion
    private void OnTriggerEnter(Collider other)
    {
          OnPickup();
          StartCoroutine(Respawn());
    }
```
Geen dubbele logica + geen comments + geen debug.logs
We gebruiken ook layer exclusion bij unity collision dus compare tag is niet nodig als hij aleen gaat colliden met de ball

2024-03-09 16:38 UTC, DanielNijkamp commented on Assets/Scripts/PowerUps/PowerUp.cs
> +}
```suggestion
    private IEnumerator Respawn()
    {
        _model.SetActive(false);
        yield return new WaitForSeconds(_respawnTime);
        _model.SetActive(true);
    }
}
```
Check of je hier collision ook uit moet doen of niet. sinds je nu aleen de visual model uit doet kan hij nogsteeds de powerup nog een keer triggeren

2024-03-09 16:38 UTC, DanielNijkamp commented on Assets/Scripts/PowerUps/PowerUp.cs
> +}
```suggestion
```
Hardcoded + comments mogen weg. maak beter een `[SerializeField] private Transform _respawnPosition` boven in de class zodat je het kan instellen

2024-03-09 16:38 UTC, DanielNijkamp commented on Assets/Scripts/PowerUps/PowerUp.cs
> +    protected abstract void OnPickup(); // To be implemented in derived classes
```suggestion
    protected abstract void OnPickup();
```
Zet deze method beetje onderaan alle public/private methods zodat de class wat meer georganizeerd is

2024-03-09 16:38 UTC, DanielNijkamp commented on Assets/Scripts/PowerUps/DoublePoints.cs
> +    float waitForSeconds = 20f;
```suggestion
    [SerializeField] private float _effectDuration;
```
Voeg altijd een access modifier toe. ook betere benaming en niet values hard-coded

2024-03-09 16:38 UTC, DanielNijkamp commented on Assets/Scripts/PowerUps/DoublePoints.cs
> +}
```suggestion
    private IEnumerator MultiplyPoints()
    {
        _highScoreSystem.SetScoreMultiplier(2);
        yield return new WaitForSeconds(waitForSeconds);
        _highScoreSystem.SetScoreMultiplier(1);
    }
}
```
Hier ook. altijd met method een access modifier, ook geen debug.logs

2024-03-09 16:38 UTC, DanielNijkamp commented on Assets/Scripts/PowerUps/DoublePoints.cs
> +    //add life script
```suggestion
```
Hier ook comments weg ik weet niet waarom je dit hier hebt gestopt

2024-03-09 16:38 UTC, DanielNijkamp commented on Assets/Scripts/PowerUps/LifePowerUp.cs
> +}
```suggestion
public class LifePowerUp : PowerUp
{
    protected override void OnPickup()
    {
    }
}
```
Deze mag voor nu weg als life system in develop zit moet dit geupdate zijn

2024-03-09 16:38 UTC, DanielNijkamp commented on Assets/Scripts/PowerUps/LifePowerUp.cs
> +public class LifePowerUp : PowerUp
```suggestion
public class ExtraLife : PowerUp
```
Miss ook beter benaming waar we niet elke keer `Powerup` achteraan toevoegen

2024-03-09 16:38 UTC, DanielNijkamp commented on Assets/Scripts/PowerUps/DoubleBounce.cs
> +public class NewBehaviourScript : PowerUp
```suggestion
public class DoubleBounce : PowerUp
```
Altijd dit checken. ook alle comments uit de script halen AUB

2024-03-09 16:38 UTC, DanielNijkamp commented on Assets/Scripts/PowerUps/DoubleBounce.cs
> +    private bool hasAppliedEffect = false;
```suggestion
    [SerializeField] private float _effectDuration;
    private bool _appliedEffect
```
Waarom hebben we ook 2 aparte booleans voor dezelfde taak? kunnen we niet gewoon checken of de effect Geapplied is of niet?

2024-03-09 16:38 UTC, DanielNijkamp commented on Assets/Scripts/PowerUps/DoubleBounce.cs
> +    }
```suggestion
    private IEnumerator ApplyEffect()
    {
        StartCoroutine(ModifyBallPropertiesOverTime(0.8f, 0.8f, 1f));

        yield return new WaitForSeconds(_effectDuration);

        StartCoroutine(ModifyBallPropertiesOverTime(1f, 1f, 1f));
    }
```

2024-03-09 16:38 UTC, DanielNijkamp commented on Assets/Scripts/PowerUps/DoubleBounce.cs
> +}
```suggestion
    private IEnumerator ApplyEffectOverTime(float sizeMultiplier, float massMultiplier, float duration)
    {
        float elapsedTime = 0f;
        Vector3 startSize = _targetObject.transform.localScale;
        float startMass = originalMass;
        Vector3 targetSize = originalSize * sizeMultiplier;
        float targetMass = originalMass * massMultiplier;

        while (elapsedTime < duration)
        {
            _targetObject.transform.localScale = Vector3.Lerp(startSize, targetSize, elapsedTime / duration);

           rb.mass = Mathf.Lerp(startMass, targetMass, elapsedTime / duration);
           
            elapsedTime += Time.deltaTime;
            yield return null;
        }

       
        _targetObject.transform.localScale = targetSize;

         finalRb.mass = targetMass;
    }
}
```
Zovaak GetComponent gebruiken is slecht nooit doen. doe het 1 keer in de start method en sla het dan op

2024-03-09 16:38 UTC, DanielNijkamp commented on Assets/Scripts/PowerUps/DoubleBalls.cs
> +    private GameObject extraBall;
```suggestion
    [SerializeField] private GameObject _targetObject;
    [SerializeField] private float _effectDuration;
    private GameObject _copiedObject;
```

2024-03-09 16:38 UTC, DanielNijkamp commented on Assets/Scripts/PowerUps/DoubleBalls.cs
> +    IEnumerator ExtraBall()
```suggestion
    private IEnumerator Copy()
```

2024-03-09 16:38 UTC, DanielNijkamp commented on Assets/Scripts/PowerUps/DoubleBalls.cs
> +    }
```suggestion
            extraBall = Instantiate(_targetObject, transform.position, Quaternion.identity);

            yield return new WaitForSeconds(_effectDuration);
            
            Destroy(extraBall);
    }
```
Als je de collision in de base class uit zet dan hoef je ook geen boolean check

2024-03-11 14:49 UTC, RossTubes commented on Assets/Scripts/PowerUps/DoubleBounce.cs
> +}
thanks for the tip

2024-03-12 09:17 UTC, RossTubes commented on Assets/Scripts/PowerUps/DoubleBalls.cs
> +    }
got it

2024-03-12 09:17 UTC, RossTubes commented on Assets/Scripts/PowerUps/DoubleBalls.cs
> +    IEnumerator ExtraBall()
done changed

2024-03-12 09:18 UTC, RossTubes commented on Assets/Scripts/PowerUps/DoubleBalls.cs
> +    private GameObject extraBall;
removed it all

2024-03-12 15:03 UTC, Kazuma-47 requested changes
ziet er gewn goed uit heb letterlijk bij maar 2 lines een _ vergeten

2024-03-12 15:03 UTC, Kazuma-47 commented on Assets/Scripts/PowerUps/DoubleBounce.cs
> +    private float originalMass;
```suggestion
    private Vector3 _originalSize;
    private float _originalMass;
```

2024-03-12 21:57 UTC, merged