Feature/score system
DanielNijkamp/FlippinWorlds pull request #8
Opened 2024-03-01 09:14 UTC by Kazuma-47

Features Added:
-score system 
-highscore system 
- ads credits

2024-03-01 12:23 UTC, DanielNijkamp requested changes
Wel goed aleen paar changes dan is het wel echt smexy code

2024-03-01 12:23 UTC, DanielNijkamp commented on Assets/Scripts/Extentions/CodeExtentions.cs
> +    }
Ternary miss inzetten?

2024-03-01 12:23 UTC, DanielNijkamp commented on Assets/Scripts/Score/ObstacleType.cs
> +     public enum ObstacleTypes
```suggestion
    public enum ObstacleTypes
```
>:)

2024-03-01 12:23 UTC, DanielNijkamp commented on Assets/Scripts/Score/ObstacleValue.cs
> +    public int Boosters;
Kan hier getter en setters toegevoegd worden? zo ja zou het dan ook private set kunnen? zo niet maak het gwn `{get; set; }`

2024-03-01 12:23 UTC, DanielNijkamp commented on Assets/Scripts/Score/SessionScoreHandler.cs
> +    [SerializeField] private ObstacleValue _obstacleValues;
UI seperate van system maken

2024-03-01 12:23 UTC, DanielNijkamp commented on Assets/Scripts/Score/SessionScoreHandler.cs
> +public class SessionScoreHandler : MonoBehaviour , ScoreSystem
```suggestion
public class HighscoreSystem : MonoBehaviour , ScoreSystem
```
Wat meer simpeler naam misschien

2024-03-01 12:23 UTC, DanielNijkamp commented on Assets/Scripts/Score/SessionScoreHandler.cs
> +    public float _scoreMultiplier = 1;
```suggestion
    [SerializableField] private float _scoreMultiplier = 1;
```

2024-03-01 12:23 UTC, DanielNijkamp commented on Assets/Scripts/Score/SessionScoreHandler.cs
> +}
```suggestion
}
```

2024-03-01 12:23 UTC, DanielNijkamp commented on Assets/Scripts/Score/SessionScoreHandler.cs
> +                _score += (int)(_obstacleValues.Coins * _scoreMultiplier);
Misschien ipv hier point calculation te doen een aparte method aanmaken. dan hoeven we niet bij elke case * multiplier te doen. wat je misschien kan doen is met scriptable object de enum value direct zetten. dan hoev je aleen in de nieuwe method te doen: type * _scoreMultiplier

2024-03-01 12:23 UTC, DanielNijkamp commented on Assets/Scripts/Score/HighScoreHandler.cs
> +    [SerializeField] private TextMeshProUGUI _creditText;
UI mag ook weg

2024-03-01 12:23 UTC, DanielNijkamp commented on Assets/Scripts/Score/HighScoreHandler.cs
> +    public static HighScoreHandler _highScoreHandler;
```suggestion
```

2024-03-01 12:23 UTC, DanielNijkamp commented on Assets/Scripts/Score/HighScoreHandler.cs
> +    }
```suggestion
     private void Awake()
    {
        //subscribe to event
    }
```
hier kunnen we hebben dat we een OnValueChange event hebben die word gefired als punten worden toegevoegd. dan kunnen andere systemen kijken naar de nieuwe value zonder tight coupling

2024-03-01 12:23 UTC, DanielNijkamp commented on Assets/Scripts/Score/IScoreSystem.cs
> +}
Naam is niet zelfde als file. maak het IScoreSystem

De OnGameOver kan weg. AddPoints is wel nessicary.

Wat je kan doen is de IScoreSystem generic maken. zodat je bijv `IScoreSystem<T>` hebt
Dan hebben `[SerializeField] private T _value;` en een `[SerializeField] private UnityEvent<T> _onValueChanged` dat we een event hebben die de nieuwe geupdate value return.

2024-03-01 13:17 UTC, Kazuma-47 commented on Assets/Scripts/Score/SessionScoreHandler.cs
> +    [SerializeField] private ObstacleValue _obstacleValues;
oki mi habibi is weg

2024-03-01 13:17 UTC, Kazuma-47 commented on Assets/Scripts/Score/ObstacleValue.cs
> +    public int Boosters;
done

2024-03-01 13:18 UTC, Kazuma-47 commented on Assets/Scripts/Score/SessionScoreHandler.cs
> +public class SessionScoreHandler : MonoBehaviour , ScoreSystem
yipee

2024-03-01 13:58 UTC, DanielNijkamp requested changes

2024-03-01 13:58 UTC, DanielNijkamp commented on Assets/Scripts/Score/HighscoreSystem.cs
> +    private int _credits;
```suggestion
    public float ScoreMultiplier { get; set;} = 1
```

2024-03-05 08:47 UTC, DanielNijkamp requested changes

2024-03-05 08:47 UTC, DanielNijkamp commented on Assets/Scripts/Score/HighscoreSystem.cs
> +    private int _credits;
```suggestion
```
Kan toch weg?

2024-03-05 08:47 UTC, DanielNijkamp commented on Assets/Scripts/Score/HighscoreSystem.cs
> +    }
```suggestion
```
Moven naar credit-system

2024-03-05 08:56 UTC, DanielNijkamp approved these changes

2024-03-05 08:57 UTC, merged