main menu UI
DanielNijkamp/FlippinWorlds pull request #9
Opened 2024-03-04 12:32 UTC by RossTubes

made UI menu in canvas

2024-03-04 13:04 UTC, Kazuma-47 requested changes, later dismissed

2024-03-04 13:04 UTC, Kazuma-47 commented on Assets/Scripts/Menu/StartButton.cs
> +    private bool isPaused = false;
`private bool _isPaused = false;`

2024-03-05 09:02 UTC, DanielNijkamp approved these changes

2024-03-05 09:05 UTC, Kazuma-47 approved these changes
looks okidoki :))

2024-03-05 09:05 UTC, merged